### ISSUE TITLE
Documenting patterns and general API

### ISSUE THREAD

**Issue by colthreepv** [jaredhanson/electrolyte#20]
First off, I think this project has great potential.
Moved by my need to instantiate a local module before calling `IoC.create('some-module')`, I discovered `IoC.literal` API.

Can the exposed API be a little documented? Examples in README are clear, a short list of exposed methods as recap at the end would be perfect.

I think a also documenting the semantic difference between literal, factory and constructor patterns would shorten the time span adopting this project (I think a couple lines each should be enough, eventually linking to [addyosmani design patterns book](http://addyosmani.com/resources/essentialjsdesignpatterns/book/)).

A fan :+1:

**Comment by jsumners** [comment]
See https://github.com/jsumners/njs-di-example

It covers all of those patterns.

**Comment by mrgamer** [comment]
Yes I met this project alongside my github searches, really gold.
It's worth linking it in the README

**Comment by colthreepv** [comment]
Closing this as jared is back and has polished comments in the code!
