### ISSUE TITLE
Implicit factory resolution

### ISSUE THREAD

**Issue by wingedfox** [jaredhanson/electrolyte#44]
Hi!

Is there a way to ask electrolyte NOT to resolve factories?
I've stuck with @require for node-uuid module, which exposes itself as a function with additional methods and electrolyte provides function return value only, not the module.

```js
module.exports = function (uuid) {
  // uuid === 'uuid string' here
  return uuid.v4(); // error: v4 is undefined
}

module.exports['@require'] = ['node-uuid']
```

**Comment by jaredhanson** [comment]
Did you find a solution?  Can you add a comment here, to help others who may experience this issue?  Thanks.

**Comment by wingedfox** [comment]
It's became obivious when I noticed existence of
```js
ioc.node_modules()
```
