### ISSUE TITLE
change default as singleton = true

### ISSUE THREAD

**Issue by colthreepv** [jaredhanson/electrolyte#49]
Is that possible via configurable options?

Usually node files are somewhat similar to singletons, due to the require-cache, so when refactoring for electrolyte it doesn't require to add `@singleton = true` everywhere

**Comment by patrickhulce** [comment]
+1 to making it an option. I've found myself adding the annotation to nearly all of my components.

**Comment by RyanDawkins** [comment]
+1

**Comment by jaredhanson** [comment]
Closing, for reasons mentioned in https://github.com/jaredhanson/electrolyte/pull/50#issuecomment-250879301
