### ISSUE TITLE
Release 0.4.0 - IoC.create now returns promise, createAsync doesn't exist

### ISSUE THREAD

**Issue by kingjerod** [jaredhanson/electrolyte#56]
Looks like the latest release 0.4.0 got messed up. The container.create function now returns a promise, and the createAsync function shown in the docs does not exist.

**Comment by jaredhanson** [comment]
That's intentional.  The docs are out of date.

**Comment by kingjerod** [comment]
Oh, ok.

**Comment by rosesonfire** [comment]
How to create without async?

**Comment by ashleydavis** [comment]
The docs still seem to be out of date.
