### ISSUE TITLE
support for es6 module syntax

### ISSUE THREAD

**Issue by cludden** [jaredhanson/electrolyte#60]
at the moment it doesn't seem possible to use the proposed es6 module syntax with the annotations required by this module. the easiest solution would seem to be allowing custom annotations, or namespacing the annotations under a top level attribute that is a valid variable name (similar to [scatter](https://github.com/mariocasciaro/scatter))

**renaming:**
```javascript
// in index.js
import Container from 'electrolyte';

Container.configure({
  prefix: '_'
});
```

```javascript
// in foo.js
export default function(bar) {
  // ..
};

export const _singleton = true;
export const _require = ['bar'];
```

**namespacing:**
```javascript
// in index.js
import Container from 'electrolyte';

Container.configure({
  namespace: 'ioc'
});
```

```javascript
// in foo.js
export default function(bar) {
  // ..
};

export const ioc = {
  singleton: true,
  require: ['bar']
};
```

thoughts?

**Comment by jaredhanson** [comment]
My initial reaction would be to favor the namespacing-style approach.  I'm curious however, if namespacing-style approach were offered, why would you choose to export things ES6 style, vs plain-old-module style?

**Comment by cludden** [comment]
looking to the future, it'd be nice for this module to support both. having worked with both extensively, I've grown quite fond of the explicitness of the es6 module syntax. I've worked in too many codebases that have tried to use hacky solutions to support async modules by overriding exports or entirely redefining exports at runtime, that the es6 module syntax prevents. would you consider a PR that is both backwards compatible and supports the namespacing approach mentioned earlier?

**Comment by jaredhanson** [comment]
Yeah, I'd certainly consider a PR that adds ES6 support.

**Comment by cludden** [comment]
closing as I haven't found the time to do this and won't for a little while

**Comment by hoxxep** [comment]
I wonder if this would allow for module and test module namespacing — that may be one benefit of the namespacing approach?
